parameters:
#    event_request_api.example.class: EventRequest\ApiBundle\Example

services:
#    event_request_api.example:
#        class: %event_request_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
