event_request_event_index:
    path:     /
    defaults: { _controller: EventRequestEventBundle:Event:index }

event_request_event_create:
    path:     /create/{slug}
    defaults: { _controller: EventRequestEventBundle:Event:create, slug: null }

event_request_event_filter:
    path:     /xhr/filter
    defaults: { _controller: EventRequestEventBundle:Event:filter }