parameters:
#    event_request_event.example.class: EventRequest\EventBundle\Example

services:
#    event_request_event.example:
#        class: %event_request_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
