parameters:
#    event_request_user.example.class: EventRequest\UserBundle\Example

services:
#    event_request_user.example:
#        class: %event_request_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
